version: '3.9'

networks:
  dev_network:
    driver: bridge

services:
  dev_db:
      image: postgres:16.3-bullseye
      restart : always
      env_file:
        - ./.env
      ports:
        - "5433:5432"
      volumes:
        - ./scripts:/docker-entrypoint-initdb.d
      networks:
        - dev_network


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - dev_network    

name: fastapi-development